apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: 'store'
    app.openshift.io/vcs-uri: 'https://github.com/mmartofel/kuberneter-probes.git'
  labels:
    app: probes
    app.kubernetes.io/component: probes
    app.kubernetes.io/instance: probes
    app.kubernetes.io/part-of: QUARKUS_API_SERVICE
    app.openshift.io/runtime: quarkus
  name: probes
spec:
  selector:
    matchLabels:
      deployment: probes
  template:
    metadata:
     labels:
      deployment: probes
    spec:
      containers:
      - env:
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              key: DBUSER
              name: postgres-configmap
        - name: DBCONNECT
          valueFrom:
            configMapKeyRef:
              key: DBCONNECT
              name: postgres-configmap
        - name: DBPASSWORD
          valueFrom:
            configMapKeyRef:
              key: DBPASSWORD
              name: postgres-configmap
        envFrom:
          - configMapRef:
              name: orm-configmap
          - configMapRef:
              name: flyway-configmap
        startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        image: quay.io/mmartofe/probes:main
        imagePullPolicy: Always
        name: probes
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
